branch-defaults:
  development:
    environment: Breeze-Backend-Staging
  staging:
    environment: Breeze-Backend-Prod
environment-defaults:
  Breeze-Backend-Prod:
    branch: null
    repository: null
  Breeze-Backend-Staging:
    branch: null
    repository: null
global:
  application_name: Breeze-backend
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: breeze
  sc: git
  workspace_type: Application
